# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from story.v1 import story_pb2 as story_dot_v1_dot_story__pb2


class StoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_unary(
                '/story.v1.StoryService/Subscribe',
                request_serializer=story_dot_v1_dot_story__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=story_dot_v1_dot_story__pb2.SubscribeResponse.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/story.v1.StoryService/Unsubscribe',
                request_serializer=story_dot_v1_dot_story__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=story_dot_v1_dot_story__pb2.UnsubscribeResponse.FromString,
                )
        self.GetAvailableStories = channel.unary_unary(
                '/story.v1.StoryService/GetAvailableStories',
                request_serializer=story_dot_v1_dot_story__pb2.GetAvailableStoriesRequest.SerializeToString,
                response_deserializer=story_dot_v1_dot_story__pb2.GetAvailableStoriesResponse.FromString,
                )
        self.GetClientTargets = channel.unary_unary(
                '/story.v1.StoryService/GetClientTargets',
                request_serializer=story_dot_v1_dot_story__pb2.GetClientTargetsRequest.SerializeToString,
                response_deserializer=story_dot_v1_dot_story__pb2.GetClientTargetsResponse.FromString,
                )


class StoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableStories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientTargets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=story_dot_v1_dot_story__pb2.SubscribeRequest.FromString,
                    response_serializer=story_dot_v1_dot_story__pb2.SubscribeResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=story_dot_v1_dot_story__pb2.UnsubscribeRequest.FromString,
                    response_serializer=story_dot_v1_dot_story__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'GetAvailableStories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableStories,
                    request_deserializer=story_dot_v1_dot_story__pb2.GetAvailableStoriesRequest.FromString,
                    response_serializer=story_dot_v1_dot_story__pb2.GetAvailableStoriesResponse.SerializeToString,
            ),
            'GetClientTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientTargets,
                    request_deserializer=story_dot_v1_dot_story__pb2.GetClientTargetsRequest.FromString,
                    response_serializer=story_dot_v1_dot_story__pb2.GetClientTargetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'story.v1.StoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/story.v1.StoryService/Subscribe',
            story_dot_v1_dot_story__pb2.SubscribeRequest.SerializeToString,
            story_dot_v1_dot_story__pb2.SubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/story.v1.StoryService/Unsubscribe',
            story_dot_v1_dot_story__pb2.UnsubscribeRequest.SerializeToString,
            story_dot_v1_dot_story__pb2.UnsubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableStories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/story.v1.StoryService/GetAvailableStories',
            story_dot_v1_dot_story__pb2.GetAvailableStoriesRequest.SerializeToString,
            story_dot_v1_dot_story__pb2.GetAvailableStoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/story.v1.StoryService/GetClientTargets',
            story_dot_v1_dot_story__pb2.GetClientTargetsRequest.SerializeToString,
            story_dot_v1_dot_story__pb2.GetClientTargetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
